http {
    upstream blue {
        server app_blue:80;
    }

    upstream green {
        server app_green:80;
    }

    split_clients $target_env {
        90% blue;
        10% green;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://$target_env;
            proxy_set_header Host $host;
        }
    }
}
